// <auto-generated />
namespace Case518.Demo.House.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Mod201411200959 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mod201411200959));
        
        string IMigrationMetadata.Id
        {
            get { return "201411200159314_Mod-201411200959"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
